version: "3"
services:

  api:
    build: ./api
    command: gunicorn -b :8000 realtimequote.wsgi:application
    depends_on:
      - authenticator
    environment:
      - DEBUG=True
      - DB_URI=postgresql://postgres:postgres@db:5432/tradex
      - AUTHENTICATOR_URI=http://authenticator:8000
      - PROCESS_AREA=/opt/process_area
    ports:
      - "8000:8000"
    networks:
      - default
    volumes:
      - process_area:/opt/process_area/
      - static:/app/static/
    restart: on-failure
  
  authenticator:
    build: ./authenticator
    command: gunicorn -b :8000 authenticator.wsgi:application
    environment:
      - DEBUG=True
      - DB_URI=postgresql://postgres:postgres@db-authenticator:5432/authenticator
    ports:
      - "8001:8000"
    networks:
      - default
    restart: on-failure

volumes:
  process_area:
  static:

networks:
  default:
    driver: bridge