version: "3"
services:

  admin-proxy:
    build:
      context: ./admin_proxy
    depends_on:
      - api
      - authenticator
    ports:
      - "8082:80"
    restart: on-failure
    networks:
      - default
    volumes:
      - static:/opt/app/static/

  api:
    build: ./api
    command: gunicorn -b :8000 realtimequote.wsgi:application
    depends_on:
      - authenticator
    environment:
      - DEBUG=True
      - DB_URI=postgresql://postgres:postgres@db:5432/realtimequote
      - AUTHENTICATOR_URI=http://authenticator:8000
      - SIMPLE_SETTINGS=realtimequote.settings
      - DJANGO_SETTINGS_MODULE=realtimequote.settings
      - BROKER_URL=amqp://root:secret@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    networks:
      - default
    volumes:
      - static:/app/static/
    restart: on-failure
  
  authenticator:
    build: ./authenticator
    command: gunicorn -b :8000 authenticator.wsgi:application
    environment:
      - DEBUG=True
      - DB_URI=postgresql://postgres:postgres@db-authenticator:5432/authenticator
    ports:
      - "8001:8000"
    networks:
      - default
    restart: on-failure

volumes:
  static:

networks:
  default:
    driver: bridge