version: "3"
services:
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tradex
    networks:
      - default
    volumes:
      - api_data:/var/lib/postgresql/data/

  db-authenticator:
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=authenticator
    networks:
      - default
    volumes:
      - authenticator_data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:6.0.9
    platform: linux/x86_64
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - default

  rabbitmq:
    restart: always
    image: rabbitmq:3.8.9-management
    platform: linux/x86_64
    container_name: rabbitmq
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # HTTP management UI
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=secret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_data:/var/log/rabbitmq
    networks:
      - default

volumes:
  api_data:
  authenticator_data:
  redis_data:
  rabbitmq_data:

networks:
  default:
    driver: bridge